<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<<<<<<< Updated upstream
<testsuite ignored="1" hostname="Neko" failures="0" tests="1" name="Default test" time="1.215" errors="0" timestamp="2021-04-21T15:29:23 ICT">
  <testcase classname="poro.module.db.data.TaiKhoanTest" name="updateAllTest" time="1.151"/>
  <testcase classname="poro.module.db.data.TaiKhoanTest" name="selectAllTest" time="0.0">
    <ignored/>
  </testcase> <!-- selectAllTest -->
=======
<<<<<<< HEAD
<<<<<<< HEAD
<testsuite ignored="0" hostname="DESKTOP-C2QK7TO" failures="0" tests="2" name="Default test" time="0.039" errors="0" timestamp="2021-04-21T14:04:19 ICT">
  <testcase classname="poro.module.StringHelperTest" name="randomTest1" time="0.007"/>
  <testcase classname="poro.module.StringHelperTest" name="randomTest2" time="0.002"/>
=======
<testsuite ignored="0" hostname="LAPTOP-FI2LLS25" failures="2" tests="6" name="Default test" time="0.145" errors="0" timestamp="2021-04-21T13:55:19 ICT">
  <testcase classname="poro.module.FileManagerTest" name="readObjectTest" time="0.044">
    <failure type="java.lang.AssertionError" message="expected [poro.module.db.data.TaiKhoan@c88a337] but found [poro.module.db.data.TaiKhoan@1de5f259]">
      <![CDATA[java.lang.AssertionError: expected [poro.module.db.data.TaiKhoan@c88a337] but found [poro.module.db.data.TaiKhoan@1de5f259]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:617)
at poro.module.FileManagerTest.readObjectTest(FileManagerTest.java:28)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- readObjectTest -->
  <testcase classname="poro.module.FileManagerTest" name="readStringTest" time="0.012"/>
  <testcase classname="poro.module.FileManagerTest" name="readTest" time="0.013"/>
  <testcase classname="poro.module.FileManagerTest" name="writeObjectTest" time="0.004">
    <failure type="java.lang.AssertionError" message="expected [poro.module.db.data.TaiKhoan@51e69659] but found [poro.module.db.data.TaiKhoan@47e2e487]">
      <![CDATA[java.lang.AssertionError: expected [poro.module.db.data.TaiKhoan@51e69659] but found [poro.module.db.data.TaiKhoan@47e2e487]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:617)
at poro.module.FileManagerTest.writeObjectTest(FileManagerTest.java:51)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- writeObjectTest -->
  <testcase classname="poro.module.FileManagerTest" name="writeStringTest" time="0.007"/>
  <testcase classname="poro.module.FileManagerTest" name="writeTest" time="0.001"/>
>>>>>>> 024afea38e51dbe84da424271b3158290e06de70
=======
<testsuite ignored="2" hostname="Neko" failures="0" tests="1" name="Default test" time="1.218" errors="0" timestamp="2021-04-21T14:28:08 ICT">
  <testcase classname="poro.module.db.data.MuonPhongTest" name="getListByPhongNoTest" time="1.135"/>
  <testcase classname="poro.module.db.data.MuonPhongTest" name="getFullListTest" time="0.0">
    <ignored/>
  </testcase> <!-- getFullListTest -->
  <testcase classname="poro.module.db.data.MuonPhongTest" name="getListByPhongYesTest" time="0.0">
    <ignored/>
  </testcase> <!-- getListByPhongYesTest -->
<<<<<<< HEAD
>>>>>>> 817a05459ac687e7ab015db746f24ed5792114f2
=======
>>>>>>> 0828e9f9dd5ecb78730235eb544cd069251783f3
>>>>>>> 024afea38e51dbe84da424271b3158290e06de70
>>>>>>> Stashed changes
</testsuite> <!-- Default test -->
