<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="0" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-04-20T02:31:30 ICT" name="Default suite" finished-at="2021-04-20T02:31:42 ICT" duration-ms="11604">
    <groups>
    </groups>
    <test started-at="2021-04-20T02:31:30 ICT" name="Default test" finished-at="2021-04-20T02:31:42 ICT" duration-ms="11604">
      <class name="poro.MainClassTest">
        <test-method is-config="true" signature="openProject()[pri:0, instance:poro.MainClassTest@11c9af63]" started-at="2021-04-20T02:31:30 ICT" name="openProject" finished-at="2021-04-20T02:31:34 ICT" duration-ms="3530" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openProject -->
        <test-method signature="loginFail1()[pri:0, instance:poro.MainClassTest@11c9af63]" started-at="2021-04-20T02:31:34 ICT" name="loginFail1" finished-at="2021-04-20T02:31:36 ICT" duration-ms="1886" status="FAIL">
          <exception class="java.lang.IllegalArgumentException">
            <message>
              <![CDATA[Invalid key code]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IllegalArgumentException: Invalid key code
at java.desktop/sun.awt.windows.WRobotPeer.keyPress(Native Method)
at java.desktop/java.awt.Robot.keyPress(Robot.java:347)
at test.module.BigBug.keyPressMutil(BigBug.java:149)
at poro.MainClassTest.loginFail1(MainClassTest.java:44)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:45)
at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:73)
at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IllegalArgumentException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginFail1 -->
        <test-method is-config="true" signature="hideMain()[pri:0, instance:poro.MainClassTest@11c9af63]" started-at="2021-04-20T02:31:36 ICT" name="hideMain" finished-at="2021-04-20T02:31:36 ICT" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- hideMain -->
        <test-method signature="loginOk()[pri:1, instance:poro.MainClassTest@11c9af63]" started-at="2021-04-20T02:31:36 ICT" name="loginOk" finished-at="2021-04-20T02:31:39 ICT" duration-ms="3550" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at poro.MainClassTest.loginOk(MainClassTest.java:69)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:45)
at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:73)
at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginOk -->
        <test-method is-config="true" signature="hideMain()[pri:0, instance:poro.MainClassTest@11c9af63]" started-at="2021-04-20T02:31:39 ICT" name="hideMain" finished-at="2021-04-20T02:31:39 ICT" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- hideMain -->
        <test-method is-config="true" signature="closeProject()[pri:0, instance:poro.MainClassTest@11c9af63]" started-at="2021-04-20T02:31:39 ICT" name="closeProject" finished-at="2021-04-20T02:31:42 ICT" duration-ms="2559" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeProject -->
      </class> <!-- poro.MainClassTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
